# Project Euler Problem 0002
# Even Fibonacci numbers

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# NOTES:
# - https://en.wikipedia.org/wiki/Fibonacci_number

# Answer: 4613732

# initialize variables
x1 = 1
x2 = 1
x_temp = 0

y = 0

while x2 < 4000000:
    x_temp = x1 + x2
    if x_temp % 2 == 0:
        y += x_temp
    x1 = x2
    x2 = x_temp

print(y)
